### ISSUE TITLE
 Could not load file or assembly 'netstandard, Version=2.1.0.0, 

### ISSUE THREAD

**Issue by Pastis67** [fzany/3CXCallControlAPI_v16#1]
Hello and thank for bringing us the APIv16
I got this error when trying to run OMSampleCore 

`System.IO.FileLoadException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
File name: 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' ---> System.IO.FileLoadException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at OMSamples.Program.Bootstrap(String[] args)
   at OMSamples.Program.Main(String[] args) in C:\Users\admin\Desktop\3CXCallControlAPI_v16\OMSamples\Program.cs:line 93`
can you help me ?

**Comment by DoraemonYu** [comment]
@Pastis67   Hello.
Today I face the same problem.
Building is no problem, however when it run it will throw the exception about "counl not load netstandard  2.1.0.0"

I notice that these Samples was written via .NetCore2.1. 
Then I found the ".NET implementation support" from
[https://docs.microsoft.com/en-us/dotnet/standard/net-standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) and it seem that **.Net Core 2.1** was not match the **.netstandard 2.1** .

Finally I change to project's target Framework from **.Net Core 2.1** to **.Net Core 3.0**, and then it work.
Try it pls.

**Comment by olorunfemidavis** [comment]
@Pastis67, upgrade the target framework as @DoraemonYu  said.
Note that it is dangerous running the sample on a live environment.

Write to me directly at fzanyajibs@gmail.com for faster communication. .

**Comment by olorunfemidavis** [comment]
> @Pastis67 Hello.
> Today I face the same problem.
> Building is no problem, however when it run it will throw the exception about "counl not load netstandard 2.1.0.0"
> 
> I notice that these Samples was written via .NetCore2.1.
> Then I found the ".NET implementation support" from
> https://docs.microsoft.com/en-us/dotnet/standard/net-standard and it seem that **.Net Core 2.1** was not match the **.netstandard 2.1** .
> 
> Finally I change to project's target Framework from **.Net Core 2.1** to **.Net Core 3.0**, and then it work.
> Try it pls.

Thank @DoraemonYu . 
What are you working on and feel free to write me if you need specific solutions.
