### ISSUE TITLE
Null Reference Exception after Update to 16.0.641

### ISSUE THREAD

**Issue by Zalhera** [fzany/3CXCallControlAPI_v16#4]
Since we updated our 3CX Installation to the newest version 16.0.641 we're unable to establish the phone system connection.

Stack Trace: 
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.SpanHelpers.IndexOf(Byte& searchSpace, Byte value, Int32 length)
   at System.String.Ctor(SByte* value)
   at System.StubHelpers.CSTRMarshaler.ConvertToManaged(IntPtr cstr)
Aborted

Everything worked fine until we upgraded to the latest version.

**Comment by olorunfemidavis** [comment]
Hi @Zalhera ,
Are you able to connect to the Phone system now or you require remote assistance?

**Comment by Zalhera** [comment]
@fzany 
Yes, the problem with the update was that we also had to upgrade the .NET Core Runtime on our server in connection with the newest version of the 3cx Dll.
